name: tests

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: Testing

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot --silent"
          --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
          extensions: mbstring, pdo_mysql, bcmath, intl
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm i

      # (Opcional) Tus credenciales privadas de composer, deja si las usas
      - name: Add Flux Credentials Loaded From ENV
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare .env and .env.testing (opcional)
        run: |
          cp .env.example .env || true
          cp .env.example .env.testing || true

      - name: Generate APP_KEY (testing)
        run: php artisan key:generate --env=testing

      - name: Install MySQL client (for health checks)
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Wait for MySQL
        run: |
          for i in {1..40}; do
            mysqladmin ping -h 127.0.0.1 -u laravel -psecret --silent && break
            sleep 2
          done

      - name: Clear config cache
        run: php artisan config:clear

      - name: Build Assets
        run: npm run build

      - name: Run Migrations (testing)
        run: php artisan migrate --env=testing --force
        # Si tus tests dependen de datos base, usa --seed:
        # run: php artisan migrate --env=testing --force --seed

      - name: Run Tests
        run: ./vendor/bin/pest -p
