name: tests

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing
      # Clave solo para que arranque el framework en CI; no usa .env:
      APP_KEY: base64:O3m8Y3gqg2GQ0m0c5p0t7QxzYt0Wg3Vg6mJ0h4N3oPQ=
      DB_CONNECTION: sqlite
      DB_DATABASE: :memory:
      CACHE_STORE: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync
      MAIL_MAILER: array

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
          extensions: mbstring, pdo_sqlite, bcmath, intl
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Clear config cache
        run: php artisan config:clear

      - name: Build Assets (Vite)
        run: npm run build

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: ./vendor/bin/pest -p
